### ISSUE TITLE
Where to find pretrained models presented in the paper

### ISSUE THREAD

**Issue by 12Chao** [Open-Catalyst-Project/AdsorbML#2]
Hi, I was curious about are you planning to release the pretrained models mentioned in the paper or is it already released somewhere else?

**Comment by abhshkdz** [comment]
The GemNet-OC model weights used in the paper are [available here](https://github.com/Open-Catalyst-Project/ocp/blob/main/MODELS.md#s2ef-models-optimized-for-efwt). We're working on getting the relevant SCN model weights ready for release, but that might take a while.
